xenserver/python-libs

- pylintrc
- xcp/__init__.py
- xcp/accessor.py
- xcp/bootloader.py
- xcp/cmd.py
- xcp/cpiofile.py
- xcp/dom0.py
- xcp/environ.py
- xcp/logger.py
- xcp/mount.py
- xcp/net/__init__.py
- xcp/net/biosdevname.py
- xcp/net/ifrename/__init__.py
- xcp/net/ifrename/dynamic.py
- xcp/net/ifrename/logic.py
- xcp/net/ifrename/macpci.py
- xcp/net/ifrename/static.py
- xcp/net/ifrename/util.py
- xcp/net/ip.py
- xcp/net/mac.py
- xcp/pci.py
- xcp/repository.py
- xcp/version.py
- xcp/xmlunwrap.py
This is a prereq to applying `futurize`.
> Transform copyright blocks from docstrings into more conventional comments

- xcp/logger.py
Fixes the problem spotted by @edwintorok after #9 was merged
> xcp.logger: don't modify the handlers list while we're iterating over it

- requirements-dev.txt
- setup.py
- tests/test_cpio.py
- tests/test_ifrename_logic.py
- tests/test_pci.py
- xcp/accessor.py
- xcp/bootloader.py
- xcp/cpiofile.py
- xcp/dom0.py
- xcp/environ.py
- xcp/mount.py
- xcp/net/ifrename/dynamic.py
- xcp/net/ifrename/static.py
- xcp/net/mac.py
- xcp/pci.py
- xcp/repository.py
- xcp/xmlunwrap.py
This includes:
- the pass 1 run itself
- fixing things futurize breaks
- avoiding the use of `future` in favor of `six` (`future` should not have appeared it anyway, as I read the definition of pass 1)
- cleanup changes from with pylint help
> Futurize pass 1

- requirements-dev.txt
- setup.py
- tests/test_cpio.py
- tests/test_ifrename_dynamic.py
- tests/test_ifrename_logic.py
- tests/test_ifrename_static.py
- tests/test_mac.py
- tests/test_pci.py
- xcp/accessor.py
- xcp/bootloader.py
- xcp/cmd.py
- xcp/cpiofile.py
- xcp/dom0.py
- xcp/environ.py
- xcp/mount.py
- xcp/net/ifrename/dynamic.py
- xcp/net/ifrename/logic.py
- xcp/net/ifrename/static.py
- xcp/net/ifrename/util.py
- xcp/net/mac.py
- xcp/pci.py
- xcp/repository.py
- xcp/version.py
- xcp/xmlunwrap.py
Stacked PR, commits are: https://github.com/ydirson/xenserver-python-libs/compare/futurize-pass-2...ydirson:xenserver-python-libs:testcpio-py3
> Testcpio improvements, cpiofile improvements and port to py3

- run-pytype.py
- xcp/cpiofile.py
[xcp/cpiofile.py: convert to UTF-8, enables pytype checker for it](https://github.com/xenserver/python-libs/commit/f2317ce8aec3aec4e0f7ede556e9c3740bc699c3)!
Because of the conversion of it to to UTF-8, there is a one major effect:
* The pytype checker now checks the file and emits many errors (at least some are real).
* Make these errors non-fatal for CI for now. (to be fixed in upcoming PRs)
Note: The errors are still shown on the GitHub Action Summary page
and on stdout during local CI.
> xcp/cpiofile.py: covert German umlauts in comments to UTF-8, enables pytype on it

- pyproject.toml
- run-pytype.py
- tests/test_biosdevname.py
- tests/test_biosdevname_ns.py
- tests/xcptestlib_unshare.py
- xcp/net/biosdevname.py
Fixes `xcp.net.biosdevname` for Python3 by adding `universal_newlines=True`:
- Besides updating the mock test, this PR also adds a new test using `unshare()` to change the process context of the new test case into a new user namespace (biosdevname needs to run as root).
- Due to a known issue with pytest-forked (a part of pytest-xdist), the new test needs to be in a dedicated file.
PS: Because of the fixes, biosdevname and cpiofile no longer need to be excluded from the main pytype check run by run-pytype.py -> removed them from excludes!
> xcp.net.biosdevname: For Py3, add universal_newlines=True to Popen()

- pyproject.toml
- tests/test_ip.py
- xcp/net/ip.py
Fixes `xcp.net.ip.ip_link_set_name()` for Python3 and covers it with two testcases.
> Fix xcp.net.ip.ip_link_set_name() for Python3 and cover it with two testcases.

- tests/test_cmd.py
- tox.ini
- xcp/cmd.py
- xcp/compat.py
This PR enables Python3 support for `xcp.cmd`:
1. `fileContents()` uses `open()` which reads binary data a strings(are bytes in Python2)
* Gets updates to select:
* reading binary files in binary mode, returns binary data using the `bytes` type
or
* reading text files text with UTF-8 chars, returns the Unicode test using the `str` type.
2. `runCmd()` uses `Popen()` and which can likewise also open the `stdin`, `stdout`, `stderr` pipes as binary or attach text codecs to them for working with Unicode strings.
- When `inputtext` (sent to `stdin`) is specified, it's type overrides the mode depending on it's data type being `str` or `bytes`.
- If runCmd is asked to just run the command and not attach the `stdin`, `stdout`, `stderr` pipes, selecting a mode is superfluous.
- Otherwise, the …
> cmd: Support Python3.6+: Add support for Py3 Popen() and open() APIs

- tox.ini
I re-installed all my local Python environments and this forced me to notice how critical the top-level tox.ini:requires= config for the dependencies of tox itself are.
Without these taken care of, developers would run in to errors which are not easy to undertand and fix.
The problem is that for working with Python versions which are EOL since a long time like Python2.7 and 3.6, nobody cares any more and the maintainers are deploying code which is not compatible with those.
For example, to current versions of virtualenv use Python features which are only present in Python 3.7 and newer like dataclasses and from __future__ import annotations which 3.6 does not have and this then breaks the detection or the setup of environment of these older Python versions.
`tox.ini:requires=` now takes …
> tox.ini: Add requires for the tox envrionment itself and small updates

- .gitignore
- Improve developer experience when the IDE has a feature to exclude the files in .gitignore from the file browser. E.g. in VS Code: `"explorer.excludeGitIgnore": true`
- Prevent accidentally adding cache directories to the git repo
> .gitignore: Add cache directories used by CI and analysis tools

- stubs/pytest.pyi
- tests/test_sbdfi_to_nic.py
- xcp/pci.py
When importing `xcp/pci.py` in Python 3.7 or newer, this warning appears:
```py
xcp/pci.py:40: FutureWarning: Possible nested set at position 146
VALID_SBDFI = re.compile(
```
Fix it by adding the missing \ inside [\[] and inside [\]]:
```diff
-    r"  (?:[[](?P<index>[\d]{1,2})[]])?$"   # Index (optional)
+    r"  (?:[\[](?P<index>[\d]{1,2})[\]])?$"   # Index (optional)
```
The function using it, `pci_sbdfi_to_nic()` is indirectly tested by
- `xcp/net/ifrename/dynamic.py`
- `xcp/net/ifrename/static.py`
and this PR also
- adds a new dedicated test in `tests/test_sbdfi_to_nic.py` added in the 1st commit,
- which passed in the 1st commit of this PR.
(as shown by it's GitHub test results - it has a blue checkmark).
The fix of the regex is then applied in the 2nd commit.
> tests/test_sbdfi_to_nic.py : Add test for `xcp.pci.pci_sbdfi_to_nic()`

- .github/workflows/PYTHONWARNINGS-problemMatcher.json
- tox.ini
Adds a GitHub ProblemMatcher for PYTHONWARNINGS from pytest:
Examples for warnings which should be shown in the GitHub Action Summary and the Pull Request Review are:
- Unclosed files, Unclosed sockets
- Regex syntax warnings
Quote from example run: https://github.com/xenserver-next/python-libs/actions/runs/5121239216
```py
test (3.10, ubuntu-latest): xcp/repository.py#L193
unclosed file <_io.TextIOWrapper name='tests/data/repo/.treeinfo' encoding='utf-8'>
```
The warnings enabled for pytest are defined in tests/conftest.py using: 
```py
@pytest.fixture(autouse=True)
def set_warnings():
warnings.simplefilter("default")
```
Documentation:
- https://github.com/actions/toolkit/blob/main/docs/problem-matchers.md
- https://github.com/actions/toolkit/blob/main/docs/commands.md#problem-matchers
> tox.ini: Add GitHub ProblemMatcher for PYTHONWARNINGS from pytest runs

- .coveragerc
- xcp/cpiofile.py
This adds type comments to fix static type checking by mypy & pyright.
The goal is to be able to use the pyright type checker which is used by the language backend of the Python extension of vscode.
It can be also used standalone for CI/CD, even in GitHub actions.
> xcp/cpiofile.py: Add type comments to fix static type checking

- xcp/cpiofile.py
Two weeks ago when adding cast()s to bz2 types,
I merged a toplevel `import bz2` because in currently used Python builds bz2 is built-in.
It's time to remove the non-toplevel `import bz2` lines which now trigger several warnings:
```py
"Reimport 'bz2' (imported line 48)"`
```
> xcp/cpiofile.py: Fix warning: Reimport 'bz2' (imported line 48)

- tests/test_bootloader.py
- xcp/bootloader.py
`xcp/bootloader.py`: Replace `open()` with `open_with_codec_handling()`:
- for Python2, this only adds a wrapper which does nothing, and
- for Python3, this adds `encoding="utf-8", errors="replace"` to `open()`
GRUB documentation states that it uses UTF-8 for all text files (including config), so it could be conceivable to encounter UTF-8 in/for them:
https://www.gnu.org/software/grub/manual/grub/html_node/Internationalisation.html
Adds a new testcase testing the new uses or `open_with_codec_handling()` in `writeGrub()` and `writeExtLinux()`
> xcp/bootloader.py: Replace open() with open_with_codec_handling()

- tests/test_dom0.py
- xcp/dom0.py
- xcp/environ.py
Make xcp.environ and xcp.dom0 safe against raising UnicodeDecodeError() in all cases and versions:
Wrap open() using open_with_codec_handling()
- Ensures that inventory information is decoded from UTF-8 to Unicode strings properly to be future-proof.
- Fixes pylint: "Using open without explicitly specifying an encoding"
> xcp/environ.py, xcp/dom0.py: Wrap open with open with codec handling

- stubs/pyfakefs/fake_filesystem_unittest.pyi
- stubs/pytest_subprocess/fake_process.pyi
- tests/test_pci.py
- `stubs/pyfakefs/`, `stubs/pytest_subprocess/`: Add stubs for test_pci.py
- Add stubs which allow using static analysis without import errors.
`tests/test_pci.py`: Covert to functions: Simpler use of pytest-fixtures
- Covert the methods using pytest-fixtures to functions
- It makes their use much simpler (10 fewer lines; assert is wrapped by pytest)
```ts
git log -n2 -p |diffstat
stubs/pyfakefs/fake_filesystem_unittest.pyi |    2 ++
stubs/pytest_subprocess/fake_process.pyi    |   35 +++++++++++++++++++++++++++++++++++
tests/test_pci.py                           |   52 +++++++++++++++++++++-------------------------------
3 files changed, 58 insertions(+), 31 deletions(-)
```
> test_pci.py: Covert methods to functions for simpler use of pytest-fixtures

- xcp/bootloader.py
Silence `reportOptionalMemberAccess` `pyright`  errors in `xcp/bootloader.py`:
```py
bootloader.py:506:16 - error: "close" is not a known member of "None" (reportOptionalMemberAccess)
bootloader.py:540:16 - error: "close" is not a known member of "None" (reportOptionalMemberAccess)
bootloader.py:608:16 - error: "close" is not a known member of "None" (reportOptionalMemberAccess)
```
The cause is that `dst_file` is passed as Optional which can be None, and only checked using `hasattr(dstfile, None)` which does not cause `pyright` to recoginze it as not None.
Add an explicit check for it to be not Null, to fix these analysis errors in for pyright CI and vscode.
> xcp/bootloader.py: Fix pyright: reportOptionalMemberAccess

- xcp/pci.py
After merging #50, @andyhhp submitted a review comment, apply his change request.
```ts
git log -n1 -p |diffstat
pci.py |    6 +++---
1 file changed, 3 insertions(+), 3 deletions(-)
```
(BTW: In the same context, it adds `# sourcery skip: raise-specific-error` to the function to silence the warning of the Sourcery checker for raising `Exception`)
> xcp/pci.py: Update the docstring of pci_sbdfi_to_nic()

- tests/test_bootloader.py
- Verify the results from reading `tests/data/grub.cfg`:
- After verifying the initial load,
- save the loaded configuration to a temporary file and
- read them again, and re-verify the red configuration to be yield the same settings
- Fixup pylint warnings
Diffstat:
```ts
git log -n1 -p |diffstat
test_bootloader.py |   49 ++++++++++++++++++++++++++++++++++++++++++++++++-
1 file changed, 48 insertions(+), 1 deletion(-)
```
> tests/test_bootloader.py: Add missing tests and fixup pylint

- pylintrc
- tests/test_ifrename_dynamic.py
- tests/test_ifrename_logic.py
- tests/test_ifrename_static.py
Trivial minor `pylint` cleanup PR for:
* `tests/test_ifrename_dynamic.py`
* `tests/test_ifrename_logic.py`
* `tests/test_ifrename_static.py` 
Diffstat:
```js
git log -n1 -p |diffstat
pylintrc                       |    4 ++--
tests/test_ifrename_dynamic.py |    3 +--
tests/test_ifrename_logic.py   |    4 +++-
tests/test_ifrename_static.py  |    3 +--
4 files changed, 7 insertions(+), 7 deletions(-)
```
Change summary:
- `tests/test_ifrename_*.py`: Fix unused-import warnings
- `pylintrc`: allow methods with 34 characters and relax the type checking of pyright for test_ifrename_logic.py
> test_ifrename_*.py: Fixup pylint, allow method-length of 34 chars

- .coveragerc
- tests/test_logger.py
- xcp/logger.py
This PR ensures that xcp.logger works with non-ASCII characters in all Python vesrions in all cases (even in XAPI plugins with Python 3.6, when no UTF-8 locale is set).
It is split into three commits:
Make xcp.logger not raise a codec error when writing non-ASCII data without a locale set.
Add typing information to the handler variable and openLog()
The changes to `xcp/logger.py` need tests to cover the changed lines.
> xcp/logger.py: Use open_with_codec_handling() for opening log files

- tests/test_accessor.py
- tests/test_ftpaccessor.py
- xcp/accessor.py
Fix warnings in `xcp/accessor.py` and add new tests, raises code coverage by 1% according to CodeCov.
(In total, we went from 69% to 75% so far)
- [tests/test_ftpaccessor.py: Add check to cover FTPAccessor._cleanup()](https://github.com/xenserver/python-libs/pull/69/commits/578d856d64eca340bdba68eb6ee903299f05a770)
- Add a call to `FTPAccessor.access()` after `FTPAccessor.openAddress()`:
- `FTPAccessor._cleanup()` is now tested and covered.
- [xcp/accessor.py: Fix warnings on FTPAccessor.ftp not None](https://github.com/xenserver/python-libs/pull/69/commits/20f0e65aa000daf9024a4f22c95626acc9bce32b)
- Fix return value of abstract/base method Accessor.openAddress
- Cast/assert FTPAccessor.ftp because it is None before start()
- [xcp/accessor.py: Fix pylint message for import of xcp.logger …
> tests/test_ftpaccessor.py: Add check to cover FTPAccessor._cleanup()

- xcp/accessor.py
Fix warnings on identical exception handlers for OSError and IOError:
On Python >= 3.3, `IOError` is a simple alias of OSError, but that wasn't the case for 2.7:
- Catch both exceptions in the same except block, which is no change for Python2.
- Fixes the pylint warning (and eliminates duplicated code).
> xcp/accessor.py: Fix pylint-py3 warning on duplicate exceptions

- tests/test_accessor.py
- xcp/accessor.py
- Test `openAddress()` of HTTPAccessor, FileAccessor and FilesystemAccessor
- TODO for an upcoming PR: Fix/Test reading a binary file as well
- Fix pylint:argument-differs:
FTPAccessor.access(path) does not match Accessor.access(name)
(arguments-differ in overridden method).
- Disable the warning to not break any existing calls which might use
these calling arguments:
- FTPAccessor.access(path=...)
- (any other)Accessor.access(name=...)
(To be sure, grep/pylint would have to be used in all callers)
- Fix not assigning a value to the builtin "file".
- Fix indentation of closing "}"
> tests/test_accessor.py: Test File* and HTTPAccessor.openAddress()

- xcp/repository.py
Simple 2-line PR:
* Fixup the unclosed file warning which was introduced by commit 08f000
(xcp.repository: switch from ConfigParser to configparser) from PR #27.
* PS: Because I'm using pre-commit now:
Also remove a line which had trailing spaces
> xcp/repository.py: Fixup unclosed file warning left from #27

- tests/test_accessor.py
- tests/test_mountingaccessor.py
- xcp/accessor.py
- [tests/test_mountingaccessor.py: Check MountingAccessor 404 handling](https://github.com/xenserver/python-libs/commit/f3cf25bdd5b32a5e37251735ece75445511dd5f2)
Test error handling and get coverage for trying to access a nonexisting file
- [tests/test_accessor.py: Update test of FileAccessor](https://github.com/xenserver/python-libs/commit/2a5db65991132030096c187b78cd4ae4c70f8e54)
Update tests of FileAccessor to verify FileAccessor.writeFile()
- [xcp/accessor.py: Update FileAcessor.writeFile() to support binary files](https://github.com/xenserver/python-libs/commit/46546a1a6525237060f3c8beed84d8aaf34ca962)
In line with all other Accessor.writeFile() implementations before, use binary mode for writing files as needed to write compressed archives.
> Update FileAcessor.writeFile() to support writing binary files

- tests/test_ftpaccessor.py
- tests/test_httpaccessor.py
- tests/test_mountingaccessor.py
- xcp/accessor.py
- xcp/repository.py
The commits on this PR depend on the 1st commit:
It adds `Accessor.openText()` as a new API to make uses like `ConfigParser().read_file(TextIO)` which need `TextIO`(`IO[str]`). It replaces calls like these (change commit: https://github.com/xenserver/python-libs/commit/a97be270bd9949735ecbb8f6ae25c0756775d101?diff=split)
```py
rawtreeinfofp = access.openAddress(cls.TREEINFO_FILENAME)
if sys.version_info < (3, 0) or isinstance(rawtreeinfofp, io.TextIOBase):
treeinfofp = rawtreeinfofp
else:
treeinfofp = io.TextIOWrapper(rawtreeinfofp, encoding='utf-8')
treeinfo = configparser.ConfigParser()
treeinfo.read_file(treeinfofp)
if treeinfofp != rawtreeinfofp:
treeinfofp.close()
rawtreeinfofp.close()
```
with:
```py
with access.openText(cls.TREEINFO_FILENAME) as fp:
treeinfo.read_file(fp)
```
It …
> Add Accessor.openText() as context manager for openAddress()

- xcp/net/ip.py
[xcp/net/ip.py: Fix logged ip exit status when ip up fails](https://github.com/xenserver/python-libs/commit/239cfcb7ff983a7cb4269340d58433ed4c2d7a05)
`ip_link_set_name()`: Fix the logged error code when `link_up` fails:
Log `link_up.returncode` when `link_up` fails, not `link_down.returncode`
When the error handling of "`link_up`" was copied from "`link_down`",
the logged error code should have been updated to `link_down.returncode`.
(Found when looking at pyright/pylance/vscode static analysis messages)
> xcp.net.ip.ip_link_set_name(): Fix the logged error code when link_up fails

- xcp/cpiofile.py
Simple PR only affecting type annotations of `xcp/cpiofile.py`:
- [xcp/cpiofile.py: Fix typing of CpioFile.*open() methods](https://github.com/xenserver/python-libs/pull/79/commits/d14fd23e80a8cb2231695e8b3d1a62ac7de1382a)
- CpioFile.cpioopen(): `name` is `None` when `fileobj` is passed
- Change typing from private types of `bz2` to `str` and `Literal`
- [xcp/cpiofile.py: Use Optional[arg] as type for optional arg](https://github.com/xenserver/python-libs/pull/79/commits/4cec27dc1ee60b5ccccb008991e64b71dfaf79c5)
- Use `Optional[arg]` when arg is optional instead of `arg|None`
(to be more specific and more clear to read)
- [xcp/cpiofile.py: Make typing fileobj more exact: IO[bytes]](https://github.com/xenserver/python-libs/pull/79/commits/a699eb53dc63c8f904a54e730cb611546c0debd6)
- Make …
> cpiofile:  Update method signatures

- xcp/cpiofile.py
Please review #83 before this PR (the first 5 commits are from it).
The remaining commits are:
- [xcp/cpiofile.py: Add type signature to `CpioFileCompat.__init__()`](https://github.com/xenserver/python-libs/pull/83/commits/3a491647f44870e6adce231bb2da8d14e8e3b0c4)
- Add type signature to `CpioFileCompat.__init__()`
- Cleanup setting member variables which are never red
(e.g. CpioInfo.name has the inode name, not .filename, etc)
- [xcp/cpiofile.py: Add type signature to _getmember()](https://github.com/xenserver/python-libs/pull/83/commits/a79d2211dd6a148c6beb8a85ff3dcf381da6d56b)
- add type signature
- add missing default return (required by `mypy`)
- [xcp/cpiofile.py: Add type signature to getmember(), extractfile()](https://github.com/xenserver/python-libs/pull/83/commits/3992d0387359948 …
> xcp/cpiofile.py: Add type signature to CpioFileCompat.__init__()

- tests/test_cpio.py
- tests/test_cpiofile.py
- xcp/cpiofile.py
On top of #84 (9 commits - review it first - they are here to have better code coverage):
* add one commit:
* Fix pyright warnings in the _CMPProxy class
> xcp/cpiofile.py: Fix pyright warnings in the _CMPProxy class

- .coveragerc
- xcp/dom0.py
Fix Pylint in xcp/dom0:
- Unnecessary "elif" after "return":
- remove the leading "el" from "elif"
- Unnecessary "else" after "return":
- remove the "else" and de-indent the code inside it (no-else-return)
- Raising too general exception "Exception": Using RuntimeError instead
> xcp/dom0.py: Fix pylint msgs like unnecessary else/elif after return

- tests/test_cpio.py
- tests/test_dom0.py
- xcp/dom0.py
- xcp/repository.py
Fix pylint warnings:
- XCP:
- xcp/repository.py: Unnecessary parens
- xcp/dom0.py:  - Consider merging these comparisons with "in" to: unit in ('k', '')
- Tests:
- tests/test_cpio.py: reimport and obsolete FIXME (the warning in that case is ok)
- tests/test_dom0.py:
- unnecessary semicolons
- Variables "M" and "G" doesn't conform to '[a-z_][a-zA-Z0-9_]{0,30}$'
(used for MegaBytes and GigaBytes only)
> pylint for repository: Fix Unnecessary parens, dom0: unit in ("k", '')

- xcp/accessor.py
Fix static analysis warnings from url splitting by urllib.parse.urlsplit:
* Static analysis tools warn that `url_parts` from `urllib.parse.urlsplit()` like `password` may be `None`:
* Check them in such way that tools are satisfied
> xcp/accessor.py: Fix analysis warnings in HTTP Basic Auth

- pylintrc
- run-pylint.py
Pylint: update enabled checkers
- [pylintrc: Enable import-position and import-outside-toplevel](https://github.com/xenserver/python-libs/commit/af9dda2ce312c7eada97786aab331927911fe3ae)
and disable too-many-statements as we won't refactor now. Also enable unnecessary-pass and multiple-imports.
- [run-pylint.py: No longer suppress most pylint messages](https://github.com/xenserver/python-libs/commit/9daaf03a00a5398813bcebdf9a7f1d6f08dd577b)
Now that most pylint warnings are fixed, no longer filter all minor message classes like convention and refactor, and only filter relatively harmless messages. Improve categorisation.
> run-pylint.py: No longer suppress most pylint messages

- .coveragerc
- xcp/repository.py
- Fix bare "except:": Bare except's also catch fatal exceptions like SystemExit and KeyboardInterrupt, which is why pylint warns about it. https://www.flake8rules.com/rules/E722.html
- Add init of name, version, build, originator to `__init__()` to fix warnings for init outside of `__init__()`
> xcp/repository.py: Final pylint & pyright static analysis fixes

- .github/act-serial.yaml
- .github/workflows/main.yml
- run-pytype.py
- tox.ini
Note: Because of the announcement of removal of Python 2.7 for setup-python in https://github.com/actions/setup-python/issues/672, use a wrapper for setup-python which can build missing Python versions.
- [run-pytype.py: Empty the list of excludes and xfails](https://github.com/xenserver/python-libs/commit/bae99960b42b5d0a952c35d1969b7af57d1892fd)
* As pytype errors are fixed, clear excludes and xfails
- [tox.ini and CI: Move pytype to Py3.8 and remove 3.7 and 3.9 builds](https://github.com/xenserver/python-libs/pull/93/commits/2f6fdd833e4299a85223e23fe623df620e101b8c)
- pytype has several problems to import libraries when used on Python 3.10, therefore move it Python 3.8.
- tox.ini, GitHub CI: Remove builds for 3.7 and 3.9 builds because they showed intermittent pytest failures and we …
> Handle GitHub removing Py27 and move pytype from to Py3.8 to fix issues

- run-pylint.py
Implement suggestion from code quality check:
- To reduce the complexity of the main function, extract the markdown generator into new function
> run-pylint.py: Extract markdown generator into new function

- .github/act-serial.yaml
- .github/workflows/main.yml
- pyproject.toml
- tox.ini
Two closely related commits:
Pin tox to 4.5.1: tox>=4 is needed for reading the extras from
pyproject.toml while tox>=4.5.2 depends on virutalenv>=20.23,
which breaks Python 2.7 in turn.
Fix the config file for testing GitHub action runs locally to pin tox to 4.5.1 (see previous commit) and fix Python 2.7
> Pin tox to 4.5.1,update act workflow

- .github/workflows/pytype.cfg
- .pre-commit-config.yaml
- run-pylint.py
- `run-pylint.py`: Fix pytype errors in CI script run-pylint.py
- `.github/workflows/pytype.cfg`: Enable checking /*.py as well    
- and use all CPUs for parallel checking
- and tolerate pyi-error and ignored-type-comment (comments which other tools use)
> Fix run-pylint.py for pytype

- .actrc
- CONTRIBUTING.md
- README.md
Add CONTRIBUTING.md with references how to setup a full development and test environment.
- Describe how to use the `act` tool to test CI changes locally can be installed on Ubuntu and Fedora.
- Describe how to install additional Python versions, static type checkers, the test runner tox, all development dependencies, pytest plugins for development and give tips for setting up WSL2/Windows for development.
> CONTRIBUTING.md, README.md: Update documentation for contributors

- stubs/pytest_httpserver.pyi
- xcp/mount.py
- xcp/pci.py
- xcp/version.py
- xcp/xmlunwrap.py
Four minor cosmetic updates:
- [xcp/pci.py: Fix pylint Unnecessary parens after 'not' keyword](https://github.com/xenserver/python-libs/commit/8089b121434573d2d27865c50e190235b131c190)
- Fix pylint warning superfluous-parens (Unnecessary parens after 'not')
- [xcp/version.py: Add missing type annotations and merge asserts](https://github.com/xenserver/python-libs/commit/0c01be201b5d8e87dddf70b8cac405fd8450ffd5)
- [xcp/xmlunwrap.py: Fix false positive from raise in six.raise_from()](https://github.com/xenserver/python-libs/commit/872472629676b76076421247e0fa5c9735774c6f)
- [stubs/pytest_httpserver.pyi: Silence pylint warnings](https://github.com/xenserver/python-libs/commit/d63fef1f8e8cd0d21add90218b5c30133673d9a4)
> Minor cosmetics

- run-pyre.py
- `run-pyre.py`: Fix pyright and pytype warnings in CI script run-pyre.py
> run-pyre.py: Fix pyright warnings in CI script run-pyre.py

- tests/test_cmd.py
- tests/test_mountingaccessor.py
- xcp/cmd.py
- xcp/compat.py
Revert a change I had made without having had checked the use of `runCmd()` in host-installer:
Thus, no longer require an additional mode argument (all uses in host-installer return text, not binary data) to be able to use the same code for host-installer:
- [xcp/compat.py: open_defaults_for_utf8_text() Default to text mode](https://github.com/xenserver/python-libs/pull/107/commits/86180c07b71ba78b6bb200c74760eaac354a0882)
- For xcp.cmd.runCmd() to be compatible with host-installer's runCmd, make `mode="r"` the default for runCmd(all commands in host-installer return text, not binary data to the caller)
- [tests/test_mountingaccessor.py: Fix tests to not mock xcp.cmd.runCmd()](https://github.com/xenserver/python-libs/pull/107/commits/b88317df57f7ad06f96949bd09a2387bf17a4deb)
- Test …
> Make runCmd() default to text; compatible with host-installer code

- tests/test_cmd.py
- tests/test_mountingaccessor.py
- xcp/cmd.py
- xcp/compat.py
xcp/mount.py: Fix or silence pyright warnings
> xcp/mount.py: Fix or silence pyright warnings

- .github/act-serial.yaml
- .github/workflows/main.yml
When an update is pushed to a PR, branch or tag, cancel currently running workflows on the same when a new workflow is triggered.
Other repos have similar cancel-in-progress in place as well:
https://github.com/spack/spack/blob/ba7ae2c153761d505063ac6727b8c939b2283ea1/.github/workflows/ci.yaml#L14C68-L14C85
This reduces compute usage when new changes are pushed when previous GitHub CI jobs were still running.
> .github/workflows/main.yml: Cancel obsolete GitHub workflows

- tox.ini
Initially, the pytest report for the GitHub Actions summary was overly verbose with a too large Markdown table:
* Re-enable the mdreport as a summary (less verbose) for verifying executed and skipped tests.
> GitHub CI/tox.ini: Re-enable test report in GitHub Actions summary

- .github/act-serial.yaml
- .github/workflows/main.yml
- tests/test_ifrename_logic.py
- tox.ini
My 1st try to fix Python 2.7 CI after GitHub dropped it was to use an action wrapping GitHub's setup-python action.
But this stopped working for Python 2.7, so this reverts to GitHub's action again
and uses apt-get install for Python 2.7 on Ubuntu 20.04
It has to rearrange the jobs again among the Ubuntu 20.04 and 22.04 images
to use Ubuntu 20.04 for Python 2.7.
> Next PRs: I have 2 minor PRs for fixing the CI infrastructure to submit after this PR.
> GitHub CI with tox: Fix Python 2.7 CI to use apt-get install

- setup27.py
setup27.py: add as temporary workaround for missing pip2 in XenServer Koji until Python2 support can be dropped: It is named setup27.py so it is only used when called explicitly: The installation for Python2 uses `python2 setup27.py install`
> setup27.py add as temporary workaround for missing pip2

- .pre-commit-config.yaml
- tests/test_httpaccessor.py
Two commits:
- Improve the test for xcp.accessor.HTTPAccessor():
- test it using URL-encoded Unicode user & password
- Fix pre-commit:
- Run the check for `dont-commit-to-master` early
- Fix running `pytype` (config was moved to `pyproject.toml`)
> HTTPAccessor: test URL-encoded Unicode user & pw, and fix pre-commit

- pyproject.toml
- xcp/bootloader.py
Fix CP-41302 for pre-commit and GitHub CI.
Also order the imports: Needed to fix `pylint` checks and `darker`
These fixes also add the needed setting of `pythonpath = ".:stubs"` in the `[tool.pytype]` section of `pyproject.toml` to make `pytype` find the fallback `stubs/branding.py`.
This configuration is also needed to fix that `pytype` can now be run without setting any `PYTHONPATH` (manually and in tools which call it) beforehand.
> xcp/bootloader.py: Fix CP-41302 for pre-commit and github CI

- xcp/bootloader.py
MenuEntry has `extra` attr defined to `None` in its constructor, Thus always got `extra` attr, and default to `None`. Try to access `extra` attr would never got `AttributeError`, and thus got value default to `None`. However, the expected default value should be ` `
Set extra value by checking whether extra got a valid value
> Set MenuEntry extra if it has valid value

- pyproject.toml
- xcp/net/ifrename/dynamic.py
This logic dates back to the XenServer 6.x days using Python 2.4.
simplejson was merged into the Python 2.5 standard library.
> Remove the use of simplejson

- xcp/net/biosdevname.py
USB network cards are assigned names using various rules. They can be usbX, ethX, wanX or wwanX based on different features. Our interface rename code bails out if the name is not in ethX format so ignore them.
> CA-389988: Do not consider USB network cards not named ethX

- .github/workflows/main.yml
- .pre-commit-config.yaml
- pytest.ini
- tests/test_biosdevname.py
- tests/test_httpaccessor.py
- tests/test_ifrename_dynamic.py
- tests/test_mountingaccessor.py
- xcp/net/biosdevname.py
Re-creating #130 - GitHub closed #130 due to a wrong push and I can't re-open it.
The 1st commit of this PR (same as #130) has already been approved by andyhhp and liulinC:
- This means the code change is already approved, but we need to fix CI as well (2nd commit)
rosslagerwall wrote in #130:
> biosdevname opens /dev/mem to read the $PIR PCI interrupt routing table. This fails with Secure Boot enabled and causes a warning in the kernel. log. Since the $PIR PCI interrupt routing table is used for routing PCI interrupts to ISA IRQs, it is not useful on any modern system so pass "-x" to biosdevname to avoid this behaviour.
Added 2nd commit to fix CI:
Note: No code changes to the xcp libraryL
- It only fixes the tests and the CI configuration to pass.
Full changelog of the 2nd commit to …
> CA-392459: Avoid opening /dev/mem when calling biosdevname

- tox.ini
Add an `mkdir -p` to create the parent directory for `$GITHUB_STEP_SUMMARY` before writing to it.
> tox.ini: Create directory for GITHUB_STEP_SUMMARY before writing it

- pyproject.toml
- tests/test_ifrename_dynamic.py
The duplicated code was detected by a specialized tool, and it prepared merging them for me as well.
I reviewed the work and moved the common functions so that the change is easy to review.
```py
$ git log -n1 -p | diffstat
pyproject.toml                 |    2 +-
tests/test_ifrename_dynamic.py |   44 ++++++++++++++------------------------------
2 files changed, 15 insertions(+), 31 deletions(-)
```
The change to `pyproject.toml` is needed to make the max-columns for `black` less wide:
It stops `black` from create an overlong joined line in the context of the diff.
The plan would be anyways to make the code formatting less wide.
It's a good find that the columns (were 96) was too wide, and this improves it.
> tests/test_ifrename_dynamic: Merge duplicate code into common functions

- pyproject.toml
- tests/test_cpiofile.py
Two commits for fixing CI:
- `tests/test_cpiofile.py`: [Fix CI] Suppress false positive of pyre about non-existing pytest.raises()
- `pyproject.toml`: pin the current pyre version to prevent more surprises
> [Fix CI] Suppress false positive of pyre about nonexisting pytest.raises()

- .pre-commit-config.yaml
- pyproject.toml
- tests/test_cpiofile.py
Update the config file for the `pre-commit` tool that can be used to run tests and checks locally:
`.pre-commit-config.yaml`: `mypy` wants `types-toml` now, add it as dependency
The other two commits are from #134, which is needed to fix the GitHub Actions CI.
> .pre-commit-config.yaml: mypy wants types-toml now, add it as dependency

- tox.ini
One commit to fix the local pytest test using pre-commit hook (which then calls tox):
tox.ini: Fix local pre-commit:
- Add missing space between the `sed` expression and the filename
> tox.ini: Fix local pre-commit: Add missing space between re and file

- tests/test_cpiofile.py
`tests/test_cpiofile.py`: Fix test to not be skipped for Python2
> tests/test_cpiofile.py: Fix test to not be skipped for Python2

- .pre-commit-config.yaml
.pre-commit-config.yaml: Update hooks and fix mdformat hook
> .pre-commit-config.yaml: Update hooks and fix mdformat hook

- .vscode/ltex.dictionary.en-US.txt
- tests/test_cpiofile.py
- xcp/cpiofile.py
Add two more checks to `tests/test_cpiofile.py`:
```py
if archive_mode.startswith("|"):  # Non-seekable streams raise StreamError
with pytest.raises(StreamError):
archive.extractfile("symlink")
else:  # Expect a seekable fileobj for this test (not a stream) to work:
fileobj = archive.extractfile("symlink")
assert fileobj and fileobj.read() == binary_data
```
```py
for comp in ["cpio", "gz", "bz2", "xz"]:
for filetype in [":", "|"]:
if comp == "xz" and filetype == ":":
continue  # streaming xz is not implemented (supported only as file)
check_archive_mode(filetype + comp, fs)
if filetype == "|":
+               check_archive_mode(filetype + comp, fs, filename="archive." + comp)
```
- `Refactor` creating the `cpio` archive for the test into a reusable function
- Improve it to also be able …
> cpiofile: Add unittest opening a symlink as fileobj

- .github/workflows/main.yml
- pytest.ini
- tox.ini
Topic: Fix GitHub CI
- GitHub dropped support for EOL Python versions in GitHub CI
Contents:
- It has become impractical to use EOL versions like Python 2.7 & 3.6 in CI
- It has become counterproductive (hurts `pyright`) to use pyre CI, disable it for now.
- Move forward to run the unit tests with Python 3.11
A follow-up PR has been created that includes this commit and compensates for the minimal loss in code coverage:
- #144
Note:
If you have review comments, I'd like to apply them using the last PR in this series!
> `CI PR #1:` Fix GitHub CI and 'tox' for local CI on Ubuntu 24.04

- xcp/bootloader.py
Function readGrub2 parses the arguments for each entries in grub.cfg, Missing arguments would result in an error in the original code. So added logic to handle the case of an entry with no arguments (e.g. memtest86+x64.efi).
> CA-407115: Adding logic to handle boot entries without additional arguments

- xcp/repository.py
New design is to expose through xenserver-release rpm provides so it can be queried from repo
This reverts commit 465e94a52d59325fbf00f764fe9554c7a8af0b4d.
> Revert "CP53579: BaseRepository provides getRequiredUpgradePluginVersion

- tests/test_dmv.py
- xcp/dmv.py
move DMV common code to python-libs because RPU plugin calls
these functions as well
> CP-54481: support DMV RPU plugin

- .readthedocs.yml
- CONTRIBUTING.md
- DOCUMENTING.md
- README-Unicode.md
- README.md
- docs/Makefile
- docs/requirements.txt
- docs/source/accessor.rst
- docs/source/bootloader.rst
- docs/source/cmd.rst
- docs/source/compat.rst
- docs/source/conf.py
- docs/source/cpiofile.rst
- docs/source/dmv.rst
- docs/source/dom0.rst
- docs/source/environ.rst
- docs/source/include-toplevel-CONTRIBUTING.md
- docs/source/include-toplevel-DOCUMENTING.md
- docs/source/include-toplevel-README-Unicode.md
- docs/source/include-toplevel-README.md
- docs/source/index.rst
- docs/source/logger.rst
- docs/source/modules.txt
- docs/source/mount.rst
- docs/source/pci.rst
- docs/source/repository.rst
- docs/source/version.rst
- docs/source/xmlunwrap.rst
- xcp/accessor.py
- xcp/cpiofile.py
Generate Sphinx Documentation and document how to build it.
The docs/static can be opened directly in a web browser, any static site and also readthedocs.io (config included).
Sample Preview URLs:
- https://bernhard-xapipython-libs.readthedocs.io
- https://bernhard-xapi.github.io/python-libs/index.html (not fully up-to-date)
For further spelling fixes, please review #171 (for `CONTRIBUTING.md`), and the other non-draft PRs.
Merging the cleanup PRs is a precondition for making spelling fixes (those would cause conflicts otherwise).
> Generate Sphinx Documentation and document how to build it.

- CONTRIBUTING.md
- pytest.ini
Fix and cleanup remaining references to the obsoleted Pytest 6.x for Python 2.7:
This is a follow-up to #149, merged two weeks ago, for @chunjiez to provide an easier pytest environment supporting current pytest versions.
This PR completes the change from #149 by updating the remaining references in the documentation and updating and cleaning up obsolete references to old pytest versions.
> Fix/cleanup remaining Pytest-6 references for Python 2.7

- docs/source/conf.py
- tox.ini
Update CI to pass again; Add annotation for mypy in docs/source/conf.py
- Remove the temporary exclusion of `xcp/dmv.py` from the diff/patch-coverage analysis
- Update CI to pass again, fails currently due to a 0.1% calculation change.
- mypy needs a trivial type annotation in docs/source/conf.py
A simple PR without product code changes to fix CI and mypy.
> Update CI to pass again; Add annotation for mypy in docs/source/conf.py

- .pre-commit-config.yaml
- README-Unicode.md
- tox.ini
Fix Markdownlint:
- Fix Long lines
- Fix text blocks
- Exclude Sphinx-internal files that only include the README files from checking.
Base commit to pass CI:
- Remove the temporary exclusion of `xcp/dmv.py` from the diff/patch-coverage analysis
- Update CI to pass again, fails currently due to a 0.1% calculation change.
- Fix CI,
- Fix Errors from Markdown linting,
- Fix Syntax errors while highlighting code and text blocks.
> Fix Markdownlint: Fix long lines, text blocks and exclude Sphinx-internal files.

- README-Unicode.md
- tox.ini
docs: Cleanup the not used variants for the UTF-8 migration
Base commit to pass CI:
- Remove the temporary exclusion of `xcp/dmv.py` from the diff/patch-coverage analysis
- Update CI to pass again, fails currently due to a 0.1% calculation change.
A simple PR without product code changes:
- Fix CI
- Cleanup obsolete docs on possibilities to handle UTF-8 that we didn't use.
> docs: Cleanup the not used variants for the UTF-8 migration
